<a href="https://colab.research.google.com/github/2303A510G2/PDS/blob/main/LAB_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Matrix Addition and Subtraction using NumPy

import numpy as np

# Create two 3x3 NumPy arrays with random integers (range: 1-20 for clarity)
A = np.random.randint(1, 21, size=(3, 3))
B = np.random.randint(1, 21, size=(3, 3))

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

# Perform element-wise addition
add_result = np.add(A, B)

# Perform element-wise subtraction
sub_result = np.subtract(A, B)

print("\nMatrix Addition (A + B):\n", add_result)
print("\nMatrix Subtraction (A - B):\n", sub_result)

# Manual verification for one element
i, j = 1, 2  # picking element at row=1, col=2 (2nd row, 3rd column)
manual_add = A[i, j] + B[i, j]
manual_sub = A[i, j] - B[i, j]

print(f"\nVerification at element position (row={i+1}, col={j+1}):")
print(f"A[{i},{j}] = {A[i,j]}, B[{i},{j}] = {B[i,j]}")
print(f"Addition check: {A[i,j]} + {B[i,j]} = {manual_add} | From np.add: {add_result[i,j]}")
print(f"Subtraction check: {A[i,j]} - {B[i,j]} = {manual_sub} | From np.subtract: {sub_result[i,j]}")

# Comment on broadcasting
print("\nNote on Broadcasting:")
print("Since both matrices are of the same shape (3x3), no broadcasting is needed here.")
print("If one matrix had a compatible shape (like 1x3 or 3x1), broadcasting would apply.")


Matrix A:
 [[ 3 12  3]
 [12  3  6]
 [ 4  3 11]]

Matrix B:
 [[18 15  3]
 [16  5 13]
 [15  3 15]]

Matrix Addition (A + B):
 [[21 27  6]
 [28  8 19]
 [19  6 26]]

Matrix Subtraction (A - B):
 [[-15  -3   0]
 [ -4  -2  -7]
 [-11   0  -4]]

Verification at element position (row=2, col=3):
A[1,2] = 6, B[1,2] = 13
Addition check: 6 + 13 = 19 | From np.add: 19
Subtraction check: 6 - 13 = -7 | From np.subtract: -7

Note on Broadcasting:
Since both matrices are of the same shape (3x3), no broadcasting is needed here.
If one matrix had a compatible shape (like 1x3 or 3x1), broadcasting would apply.
